version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ixccore
      POSTGRES_PASSWORD: ixccore
      POSTGRES_DB: ixccore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ixccore
      RABBITMQ_DEFAULT_PASS: ixccore
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "14250:14250"
      - "14268:14268"
      - "16686:16686"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: 